// example/vue-todomvc/App.vue
<style src="./index.css"></style>

<template>
  <section class="todoapp">
    <!-- header -->
    <header class="header">
      <h1>TODOS</h1>
      <input class="new-todo"
        autofocus
        autocomplete="off"
        placeholder="What needs to be done?"
        @keyup.enter="addTodo">
    </header>
    <!-- main section -->
    <section class="main" v-show="todos.length">
      <input class="toggle-all" id="toggle-all"
        type="checkbox"
        :checked="allChecked"
      >
        <!--@change="toggleAll(!allChecked)"-->
      <label for="toggle-all"></label>
      <ul class="todo-list">
        <TodoItem
          v-for="(todo, index) in filteredTodos"
          :key="index"
          :todo="todo"
        />
      </ul>
    </section>
    <!-- footer -->
    <footer class="footer" v-show="todos.length">
      <span class="todo-count">
        <strong>{{ remaining }}</strong>
        {{ remaining | pluralize('item') }} left
      </span>
      <ul class="filters">
        <li v-for="(val, key) in filters">
          <a :href="'#/' + key"
            :class="{ selected: visibility === key }"
            @click="visibility = key">{{ key | capitalize }}</a>
        </li>
      </ul>
      <button class="clear-completed"
        v-show="todos.length > remaining"
        @click="store.commit('clearTodo')">
        Clear completed
      </button>
    </footer>
  </section>
</template>

<script>
import TodoItem from './TodoItem.vue'

const filters = {
  all: todos => todos,
  active: todos => todos.filter(todo => !todo.done),
  completed: todos => todos.filter(todo => todo.done)
}

export default {
  components: { TodoItem },
  data () {
    return {
      visibility: 'all',
      filters: filters
    }
  },
  computed: {
    todos () {
      return this.store.state.todos
    },
    allChecked () {
      return this.todos.every(todo => todo.done)
    },
    filteredTodos () {
      return filters[this.visibility](this.todos)
    },
    remaining () {
      return this.todos.filter(todo => !todo.done).length
    }
  },
  methods: {
    addTodo (e) {
      const text = e.target.value
      if (text.trim()) {
        this.store.commit('addTodo', {
          text: text,
          id: new Date().getTime()
        })
      }
      e.target.value = ''
    }
  },
  filters: {
    pluralize: (n, w) => n === 1 ? w : (w + 's'),
    capitalize: s => s.charAt(0).toUpperCase() + s.slice(1)
  }
}
</script>

// example/react-todomvc/AppComponent.js
import React, {Component} from 'react'
import './App.css'
import {RSlimConsumer} from 'rslim'
import TodoItem from './TodoItem'
import store from './store'

const filters = {
  all: todos => todos,
  active: todos => todos.filter(todo => !todo.done),
  completed: todos => todos.filter(todo => todo.done)
}

class AppComponent extends Component {
  constructor (props) {
    super(props)

    this.state = {
      visibility: 'all',
      filters: filters
    }
  }

  addTodo (e) {
    if (e.key === 'Enter') {
      const text = e.target.value
      if (text.trim()) {
        store.commit('addTodo', {
          text: text,
          id: new Date().getTime(),
          done: false
        })
      }
      e.target.value = ''
    }
  }

  remaining (todos) {
    return todos.filter(todo => !todo.done).length
  }

  filteredTodos (todos) {
    return filters[this.state.visibility](todos)
  }

  setVisible (key) {
    this.setState({
      visibility: key
    })
  }

  render () {
    return (
      <RSlimConsumer>
        {({$store, $state}) => (
          <section className="todoapp">
            <header className="header">
              <h1>TODOS</h1>
              <input className="new-todo"
                     autoFocus={true}
                     autoComplete="off"
                     placeholder="What needs to be done?"
                     onKeyPress={this.addTodo}
              />
            </header>
            <section className="main">
              <input
                className="toggle-all"
                id="toggle-all"
                type="checkbox"
                checked={this.state.allChecked}
              />
              <ul className="todo-list">
                {
                  this.filteredTodos($state.todos).map(todo => {
                    return (
                      <TodoItem todo={todo} key={todo.id}/>
                    )
                  })
                }
              </ul>
            </section>
            {
              $state.todos.length ? (
                <footer className="footer">
                  <span className="todo-count"><strong>{this.remaining($state.todos)}</strong></span>
                  <ul className="filters">
                    {
                      Object.keys(filters).map((key) => {
                        return (
                          <li key={key}>
                            <a href={'#/' + key}
                               className={
                                 `${this.state.visibility === key ? 'selected' : ''}`
                               }
                               onClick={() => {
                                 this.setVisible(key)
                               }}>{key}</a>
                          </li>
                        )
                      })
                    }
                  </ul>
                  {
                    $state.todos.length > this.remaining($state.todos) ? (
                      <button
                        className="clear-completed"
                        onClick={() => {
                          $store.commit('clearTodo')
                        }}
                      >
                        Clear completed
                      </button>
                    ) : ''
                  }
                </footer>
              ) : ''
            }
          </section>
        )}
      </RSlimConsumer>
    )
  }
}

export default AppComponent
